import type { Passage, SystemicMoment, Quest } from './types';

export const passages: Passage[] = [
  {
    id: 'harriet-tubman',
    name: 'Harriet Tubman',
    years: 'c. 1822–1913',
    text: `Harriet Tubman was born into slavery in Maryland around 1822. In 1849, she escaped to freedom in the North. She could have stayed safe, but instead she went back again and again. Using a secret network called the Underground Railroad, Tubman guided about seventy enslaved people to freedom over thirteen dangerous trips. She traveled at night, avoided slave catchers, and never lost a single passenger. Her friends called her "Moses" because she led her people, like the Bible's Moses, out of bondage. During the Civil War, Tubman also served the Union Army as a scout and spy. Her <vocab>relentless</vocab> courage never faded, even when a bounty was placed on her head.`,
    vocabWord: 'relentless',
    vocabDefinition: 'not stopping or giving up, even when things are difficult',
    funFact: 'Tubman never lost a single passenger on any of her thirteen trips.',
    arrival: 'You slip into the Maryland woods at night, 1849, just steps behind a woman moving fast and sure through the dark.',
    memorySecured: "The memory holds. Harriet Tubman's thirteen trips are anchored in the record, exactly as they happened.",
    memoryFlicker: 'The memory flickers — for a moment, the record blurs. You steady yourself and look again.',
    questions: [
      {
        kind: 'vocab',
        prompt: 'In the passage, the word "relentless" most nearly means:',
        choices: [
          'careless and confused',
          'not stopping or giving up',
          'quiet and shy',
          'brief and sudden',
        ],
        correctIndex: 1,
        explanation: 'Relentless describes courage that never faded, even with a bounty on her head — meaning it never stopped or wavered.',
      },
      {
        kind: 'main-idea',
        prompt: 'What was the Underground Railroad, as described in the passage?',
        choices: [
          'An actual railroad with trains',
          'A secret network that helped enslaved people escape',
          'A group of Union Army spies',
          'A law that ended slavery',
        ],
        correctIndex: 1,
        explanation: 'The passage says Tubman used "a secret network called the Underground Railroad" to guide people to freedom.',
      },
      {
        kind: 'inference',
        prompt: "Based on the passage, why did people call Harriet Tubman 'Moses'?",
        choices: [
          'Because that was her real name',
          'Because she wrote a famous book',
          "Because, like the Bible's Moses, she led her people out of bondage",
          'Because she was born in Egypt',
        ],
        correctIndex: 2,
        explanation: 'The passage directly compares her to Moses because she led her people out of slavery, just as Moses led his people out of bondage.',
      },
    ],
  },
  {
    id: 'frederick-douglass',
    name: 'Frederick Douglass',
    years: '1818–1895',
    text: `Frederick Douglass was born enslaved in Maryland in 1818. Enslaved people were forbidden from learning to read, but Douglass secretly taught himself letters with the help of children in his neighborhood. Reading opened his mind to the idea that slavery was wrong and could be fought. In 1838, he escaped to New York and became a powerful <vocab>abolitionist</vocab>, traveling from town to town to convince Americans that slavery must end. Douglass gave fiery speeches, wrote a bestselling autobiography, and published his own newspaper, The North Star, to spread his message further. During the Civil War, he pushed President Lincoln to let Black soldiers fight for the Union. Douglass believed that words and ideas were as powerful as any weapon.`,
    vocabWord: 'abolitionist',
    vocabDefinition: 'a person who worked to end slavery',
    funFact: 'Douglass taught himself to read and write in secret, since it was illegal to teach enslaved people.',
    arrival: 'You land in a quiet room in Maryland, where a boy is tracing letters in the dirt with a stick, hiding from view.',
    memorySecured: "The memory holds. Frederick Douglass's fight to read — and to be heard — is locked into the record.",
    memoryFlicker: 'The memory flickers. Something about the account is still hazy. Focus.',
    questions: [
      {
        kind: 'vocab',
        prompt: 'As used in the passage, "abolitionist" most nearly means:',
        choices: [
          'a person who worked to end slavery',
          'a newspaper editor',
          'a soldier in the Union Army',
          'a teacher of young children',
        ],
        correctIndex: 0,
        explanation: 'The passage shows Douglass traveling to "convince Americans that slavery must end" — that work is what makes someone an abolitionist.',
      },
      {
        kind: 'main-idea',
        prompt: 'How did Douglass spread his message, according to the passage?',
        choices: [
          'Only through private conversations',
          'By giving speeches, writing an autobiography, and publishing a newspaper',
          'By running for political office',
          'By working directly for the government',
        ],
        correctIndex: 1,
        explanation: 'The passage lists speeches, a bestselling autobiography, and his newspaper The North Star as ways he spread his message.',
      },
      {
        kind: 'inference',
        prompt: 'What does the passage suggest about the importance of reading in Douglass\'s life?',
        choices: [
          'Reading had little effect on his beliefs',
          'Reading was only useful for entertainment',
          'Learning to read helped him realize slavery was wrong and gave him the tools to fight it',
          'He never learned to read fluently',
        ],
        correctIndex: 2,
        explanation: 'The passage says reading "opened his mind" to slavery being wrong, and his skill with words later became his main tool as an activist.',
      },
    ],
  },
  {
    id: 'rosa-parks',
    name: 'Rosa Parks',
    years: '1913–2005',
    text: `On December 1, 1955, Rosa Parks boarded a bus in Montgomery, Alabama, after a long day of work. When the driver ordered her to give up her seat to a white passenger, she quietly refused. Parks was arrested, but her small act of defiance sparked a huge response. Black leaders in Montgomery organized a <vocab>boycott</vocab> of the city buses, urging riders to walk, carpool, or find any other way to get around instead of riding. For 381 days, thousands of people kept up the boycott, even in bad weather. The bus company lost so much money that the city was finally forced to end segregated seating. Parks had been a civil rights activist for years before that day, but her calm courage on the bus made her a symbol for the whole movement.`,
    vocabWord: 'boycott',
    vocabDefinition: 'an organized refusal to buy from or use something, done to force a change',
    funFact: 'The Montgomery Bus Boycott lasted 381 days before the city ended segregated seating.',
    arrival: "You're standing in the aisle of a Montgomery bus, December 1955, watching a tired woman decide not to move.",
    memorySecured: 'The memory holds. The bus, the boycott, the 381 days — all anchored, unshaken.',
    memoryFlicker: 'The memory flickers. The record wavers for a second before you catch it.',
    questions: [
      {
        kind: 'vocab',
        prompt: 'As used in the passage, the word "boycott" most nearly means:',
        choices: [
          'a type of bus route',
          'an organized refusal to use something as a protest',
          'a legal punishment for breaking a law',
          'a celebration held after a victory',
        ],
        correctIndex: 1,
        explanation: 'The passage explains that leaders organized a boycott by urging riders to avoid the buses altogether — an organized refusal used to pressure the company.',
      },
      {
        kind: 'main-idea',
        prompt: 'Why did the bus company eventually end segregated seating?',
        choices: [
          'A new law was passed overnight',
          'Rosa Parks sued the company in court',
          'It lost so much money during the 381-day boycott',
          'The bus drivers went on strike',
        ],
        correctIndex: 2,
        explanation: 'The passage says the boycott lasted 381 days and the bus company "lost so much money" that the city was forced to act.',
      },
      {
        kind: 'inference',
        prompt: "What does the passage suggest about Rosa Parks's role in the civil rights movement?",
        choices: [
          'She acted alone and had no connection to any larger movement',
          'She had no interest in civil rights before 1955',
          'She was already an activist, and her arrest became a spark that ignited a much larger protest',
          'She was a bus driver herself',
        ],
        correctIndex: 2,
        explanation: 'The passage notes Parks "had been a civil rights activist for years before that day," and her arrest "sparked" the larger boycott.',
      },
    ],
  },
  {
    id: 'martin-luther-king-jr',
    name: 'Martin Luther King Jr.',
    years: '1929–1968',
    text: `Martin Luther King Jr. was a Baptist minister who became the most famous leader of the American civil rights movement. King believed that protests should always be <vocab>nonviolent</vocab>, even when protesters were met with violence themselves. He organized marches, boycotts, and sit-ins across the South, and he was arrested many times for his activism. In August 1963, King stood before a quarter of a million people in Washington, D.C., and delivered his famous "I Have a Dream" speech, calling for an end to racism and inequality. In 1964, he became the youngest person at the time to win the Nobel Peace Prize. King was assassinated in 1968, but the laws his movement helped pass, like the Civil Rights Act, changed the country forever.`,
    vocabWord: 'nonviolent',
    vocabDefinition: 'not using physical force or violence',
    funFact: 'In 1964, King became the youngest person up to that time to win the Nobel Peace Prize.',
    arrival: "You're in the crowd at the base of the Lincoln Memorial, August 1963, the air thick with quiet expectation.",
    memorySecured: 'The memory holds. The dream Dr. King spoke of that day is locked into the record for good.',
    memoryFlicker: 'The memory flickers — the words start to blur. Steady it.',
    questions: [
      {
        kind: 'vocab',
        prompt: 'In the passage, the word "nonviolent" most nearly means:',
        choices: [
          'secret and hidden',
          'not using physical force',
          'extremely loud',
          'planned far in advance',
        ],
        correctIndex: 1,
        explanation: 'The passage contrasts nonviolent protest with the violence protesters faced, showing that nonviolent means not using physical force.',
      },
      {
        kind: 'main-idea',
        prompt: 'What happened in August 1963, according to the passage?',
        choices: [
          'King won the Nobel Peace Prize',
          'King was arrested for the first time',
          'King delivered his "I Have a Dream" speech to a quarter of a million people',
          'The Civil Rights Act was signed into law',
        ],
        correctIndex: 2,
        explanation: 'The passage states that "In August 1963, King stood before a quarter of a million people... and delivered his famous \'I Have a Dream\' speech."',
      },
      {
        kind: 'inference',
        prompt: "Based on the passage, why was King's commitment to nonviolence especially difficult?",
        choices: [
          'Because no one supported his cause',
          'Because he faced violence in return but still refused to use it himself',
          'Because nonviolent protests were against the law',
          'Because he preferred to protest alone',
        ],
        correctIndex: 1,
        explanation: 'The passage says protests stayed nonviolent "even when protesters were met with violence themselves," showing King held to his principle despite being attacked.',
      },
    ],
  },
  {
    id: 'bessie-coleman',
    name: 'Bessie Coleman',
    years: '1892–1926',
    text: `Bessie Coleman grew up picking cotton in Texas, but she dreamed of flying. In the early 1900s, American flight schools refused to train her because she was Black and a woman. Determined, Coleman learned French and traveled to France, where she earned her pilot's license in 1921 — the first African American and the first Native American woman ever to do so. Back in the United States, no one would hire her to fly for an airline, so she became a <vocab>barnstorming</vocab> pilot, thrilling crowds at air shows with daring loops, dives, and figure eights. She also refused to perform anywhere that separated Black and white spectators. Coleman died in a flying accident in 1926, but she had already inspired a generation of Black aviators.`,
    vocabWord: 'barnstorming',
    vocabDefinition: 'performing daring, showy flying stunts to entertain a crowd',
    funFact: 'Coleman had to travel all the way to France to find a flight school that would train her.',
    arrival: "You're on a French airfield in 1921, watching a young woman climb into a cockpit for the flight of her life.",
    memorySecured: "The memory holds. Bessie Coleman's license — and every loop she flew after — is anchored in the record.",
    memoryFlicker: 'The memory flickers. The sky in the record goes hazy for a moment.',
    questions: [
      {
        kind: 'vocab',
        prompt: 'As used in the passage, "barnstorming" most nearly means:',
        choices: [
          'farming in the countryside',
          'performing daring flying stunts for crowds',
          'teaching new pilots to fly',
          'repairing broken airplanes',
        ],
        correctIndex: 1,
        explanation: 'The passage describes Coleman "thrilling crowds at air shows with daring loops, dives, and figure eights," which is what a barnstorming pilot does.',
      },
      {
        kind: 'main-idea',
        prompt: 'Why did Bessie Coleman travel to France?',
        choices: [
          'To visit family',
          'Because American flight schools refused to train her',
          'To compete in an international air race',
          'To study cotton farming methods',
        ],
        correctIndex: 1,
        explanation: 'The passage says American flight schools refused to train her because of her race and gender, so she went to France instead.',
      },
      {
        kind: 'inference',
        prompt: "What does Coleman's refusal to perform at segregated air shows suggest about her?",
        choices: [
          'She only cared about her own fame',
          'She avoided controversy whenever possible',
          'She used her position to stand up against unfair treatment of Black spectators',
          'She was afraid of large crowds',
        ],
        correctIndex: 2,
        explanation: 'By refusing to perform where audiences were segregated, Coleman used her influence to push back against unequal treatment, not just to entertain.',
      },
    ],
  },
  {
    id: 'katherine-johnson',
    name: 'Katherine Johnson',
    years: '1918–2020',
    text: `Katherine Johnson loved numbers from the time she was a child, and she graduated from college at just eighteen years old. She went to work for NASA as a mathematician, at a time when Black women were placed in a separate office called the "West Computing" group. Johnson calculated the flight path, or <vocab>trajectory</vocab>, for America's first crewed spaceflight in 1961. Her work was so trusted that before his historic orbit around Earth, astronaut John Glenn asked engineers to have Johnson personally check the numbers produced by NASA's new electronic computers by hand. If her numbers matched the computer's, he said, he would trust the flight. They matched. Johnson's calculations later helped guide the Apollo 11 mission to the moon.`,
    vocabWord: 'trajectory',
    vocabDefinition: 'the curved path that an object follows as it moves through space',
    funFact: "John Glenn wouldn't fly until Katherine Johnson personally checked the computer's math.",
    arrival: "You're in a NASA office in 1961, pencils scratching, as a mathematician checks numbers no one else trusts yet.",
    memorySecured: "The memory holds. Katherine Johnson's trajectory — and Glenn's trust in it — is locked into the record.",
    memoryFlicker: "The memory flickers. A number somewhere doesn't add up yet. Look again.",
    questions: [
      {
        kind: 'vocab',
        prompt: 'In the passage, "trajectory" most nearly means:',
        choices: [
          'the fuel used by a rocket',
          'the path an object follows as it moves',
          'the weight of a spacecraft',
          'a type of mathematical equation',
        ],
        correctIndex: 1,
        explanation: 'The passage explains that trajectory refers to the flight path Johnson calculated for the spacecraft.',
      },
      {
        kind: 'main-idea',
        prompt: "Why did John Glenn want Katherine Johnson to check the computer's numbers by hand?",
        choices: [
          'The computer was broken',
          "He trusted her calculations and wanted to confirm the computer's results matched hers",
          'NASA did not own enough computers',
          'Johnson had invented the computer',
        ],
        correctIndex: 1,
        explanation: "The passage says Glenn wanted Johnson to check the numbers because he trusted her math, and he would only fly if her numbers matched the computer's.",
      },
      {
        kind: 'inference',
        prompt: "What does the passage suggest about the value of Katherine Johnson's work at NASA?",
        choices: [
          "It was considered unimportant compared to the engineers' work",
          "It was so trusted that a famous astronaut's safety depended on her checking it",
          'It was only used for minor calculations',
          'It was replaced entirely once computers were invented',
        ],
        correctIndex: 1,
        explanation: "Glenn trusted Johnson's calculations enough to base his willingness to fly on whether they matched the computer, showing how vital her work was.",
      },
    ],
  },
  {
    id: 'jackie-robinson',
    name: 'Jackie Robinson',
    years: '1919–1972',
    text: `In 1947, Jackie Robinson stepped onto the field as a Brooklyn Dodger and broke Major League Baseball's color line, becoming the first Black player in the modern era. Team executive Branch Rickey had warned Robinson that he would face terrible abuse — insults, threats, and even opposing players trying to injure him — and asked him to respond without fighting back. Robinson agreed, showing incredible <vocab>restraint</vocab> as fans and opponents hurled racist insults at him game after game. He let his performance on the field speak instead, winning Rookie of the Year in 1947 and the National League MVP award in 1949. Robinson's success proved that Black athletes belonged in the major leagues and opened the door for the integration of professional sports.`,
    vocabWord: 'restraint',
    vocabDefinition: 'the ability to control your feelings or actions, especially when provoked',
    funFact: 'Robinson won Rookie of the Year in 1947 and league MVP just two seasons later, in 1949.',
    arrival: "You're behind home plate, 1947, watching a rookie absorb insult after insult without ever swinging back off the field.",
    memorySecured: "The memory holds. Jackie Robinson's restraint — and his record — are anchored for good.",
    memoryFlicker: 'The memory flickers. Somewhere in the record, the story wavers.',
    questions: [
      {
        kind: 'vocab',
        prompt: 'As used in the passage, "restraint" most nearly means:',
        choices: [
          'controlling your feelings or actions instead of reacting',
          'a special piece of baseball equipment',
          "a rule written into baseball's official handbook",
          'a type of injury',
        ],
        correctIndex: 0,
        explanation: 'The passage shows Robinson responding to abuse "without fighting back," which is what restraint means — controlling your reaction instead of lashing out.',
      },
      {
        kind: 'main-idea',
        prompt: 'What did Branch Rickey ask Jackie Robinson to do?',
        choices: [
          'Quit baseball after one season',
          'Face abuse without fighting back',
          'Train other Black players',
          'Move to a different team',
        ],
        correctIndex: 1,
        explanation: 'The passage states Rickey "asked him to respond without fighting back" despite the abuse Robinson would face.',
      },
      {
        kind: 'inference',
        prompt: "Based on the passage, why was Robinson's approach effective in changing baseball?",
        choices: [
          'He avoided all attention from fans and media',
          'He let his skill on the field prove Black players belonged, rather than reacting to insults',
          'He refused to play until conditions improved',
          'He convinced Rickey to ban all opposing teams',
        ],
        correctIndex: 1,
        explanation: 'The passage says Robinson "let his performance on the field speak," and his success "proved that Black athletes belonged," showing that his skill, not conflict, changed minds.',
      },
    ],
  },
  {
    id: 'madam-cj-walker',
    name: 'Madam C.J. Walker',
    years: '1867–1919',
    text: `Sarah Breedlove was born in 1867 to formerly enslaved parents in Louisiana. After struggling with her own hair loss, she developed a line of hair care products made especially for Black women, and rebranded herself as Madam C.J. Walker. Rather than just selling her products in stores, Walker built a <vocab>self-made</vocab> business empire by training thousands of Black women as sales agents who sold door to door and earned real income of their own. By the early 1900s, Walker had become one of the first American women, of any race, to become a millionaire. She spent much of her fortune funding scholarships, orphanages, and civil rights organizations, believing that Black economic success was tied to Black freedom.`,
    vocabWord: 'self-made',
    vocabDefinition: 'having become successful through your own hard work rather than inherited wealth',
    funFact: 'Walker trained thousands of Black women as sales agents, giving them their own source of income.',
    arrival: "You're in a parlor in the early 1900s, where a woman is mixing the first batch of a product that will become an empire.",
    memorySecured: "The memory holds. Madam C.J. Walker's rise — and everyone she lifted with her — is anchored in the record.",
    memoryFlicker: 'The memory flickers. Part of the ledger is still smudged. Focus.',
    questions: [
      {
        kind: 'vocab',
        prompt: 'In the passage, "self-made" most nearly means:',
        choices: [
          'inheriting money from a wealthy family',
          'becoming successful through your own hard work',
          "working for someone else's company",
          'borrowing money to start a business',
        ],
        correctIndex: 1,
        explanation: "The passage describes Walker building her fortune herself, from a personal struggle to a business empire, which is what \"self-made\" describes.",
      },
      {
        kind: 'main-idea',
        prompt: "How did Madam C.J. Walker build her business, according to the passage?",
        choices: [
          'By opening a single store in Louisiana',
          'By training thousands of women as sales agents who sold door to door',
          'By inheriting a hair care company',
          'By working exclusively with department stores',
        ],
        correctIndex: 1,
        explanation: 'The passage says Walker "built a self-made business empire by training thousands of Black women as sales agents."',
      },
      {
        kind: 'inference',
        prompt: "What can you infer about Walker's beliefs from how she used her fortune?",
        choices: [
          'She believed money should only benefit her own family',
          "She believed economic success for Black Americans was connected to their freedom and opportunity",
          'She had no interest in civil rights',
          'She wanted to keep her wealth a secret',
        ],
        correctIndex: 1,
        explanation: 'The passage says she funded scholarships, orphanages, and civil rights groups because she believed "Black economic success was tied to Black freedom."',
      },
    ],
  },
  {
    id: 'shirley-chisholm',
    name: 'Shirley Chisholm',
    years: '1924–2005',
    text: `In 1968, Shirley Chisholm became the first Black woman elected to the United States Congress, representing part of New York. She was known for being outspoken and independent, refusing to simply go along with what powerful party leaders wanted. Her campaign slogan, "unbought and <vocab>unbossed</vocab>," captured her promise that no one — not wealthy donors, not political parties — would control her votes. In 1972, Chisholm made history again by running for President of the United States, becoming the first Black candidate to seek a major party's nomination. She did not win, but her campaign opened doors for the many women and people of color who ran for president after her.`,
    vocabWord: 'unbossed',
    vocabDefinition: 'not controlled or told what to do by anyone',
    funFact: "Chisholm's 1972 presidential run made her the first Black candidate to seek a major party's nomination.",
    arrival: "You're in a campaign office, 1972, surrounded by handmade signs that read 'unbought and unbossed.'",
    memorySecured: "The memory holds. Shirley Chisholm's run — and every door it opened after — is locked into the record.",
    memoryFlicker: 'The memory flickers. The slogan on the wall blurs for a second. Steady it.',
    questions: [
      {
        kind: 'vocab',
        prompt: 'As used in the passage, "unbossed" most nearly means:',
        choices: [
          'unemployed',
          'not controlled or told what to do by anyone',
          'extremely wealthy',
          'newly elected',
        ],
        correctIndex: 1,
        explanation: 'The passage explains her slogan meant that "no one... would control her votes," which is what "unbossed" describes.',
      },
      {
        kind: 'main-idea',
        prompt: 'What did Shirley Chisholm accomplish in 1972?',
        choices: [
          'She was elected President of the United States',
          "She became the first Black candidate to seek a major party's presidential nomination",
          'She retired from Congress',
          'She wrote a bestselling book',
        ],
        correctIndex: 1,
        explanation: 'The passage says that in 1972 she became "the first Black candidate to seek a major party\'s nomination."',
      },
      {
        kind: 'inference',
        prompt: "What does the passage suggest about the impact of Chisholm's 1972 campaign?",
        choices: [
          'It had no lasting effect on politics',
          'It discouraged other candidates from running',
          'It helped open the door for future women and candidates of color to run for president',
          'It ended her political career immediately',
        ],
        correctIndex: 2,
        explanation: 'The passage states her campaign "opened doors for the many women and people of color who ran for president after her."',
      },
    ],
  },
  {
    id: 'garrett-morgan',
    name: 'Garrett Morgan',
    years: '1877–1963',
    text: `Garrett Morgan was a Black inventor and businessman in Cleveland, Ohio, in the early 1900s. Worried about the number of accidents at busy intersections, Morgan patented an early version of the traffic signal that included a warning position between "stop" and "go," an <vocab>innovation</vocab> that gave drivers time to slow down safely. Morgan also invented a safety hood, an early type of gas mask, designed to help people breathe in smoky or toxic air. In 1916, when a tunnel under Lake Erie flooded with toxic gas and trapped a crew of workers, Morgan and his brother put on his safety hoods and went in themselves, rescuing several trapped men. Many of Morgan's inventions later became standard safety equipment used around the world.`,
    vocabWord: 'innovation',
    vocabDefinition: 'a new idea, method, or invention',
    funFact: 'Morgan used his own gas mask invention to rescue trapped workers from a flooded tunnel in 1916.',
    arrival: "You're at the mouth of a flooded tunnel under Lake Erie, 1916, watching two brothers pull safety hoods over their faces.",
    memorySecured: "The memory holds. Garrett Morgan's inventions — and the rescue that proved them — are anchored in the record.",
    memoryFlicker: "The memory flickers. Smoke fills the record's edges for a moment. Focus and try again.",
    questions: [
      {
        kind: 'vocab',
        prompt: 'In the passage, "innovation" most nearly means:',
        choices: [
          'a new idea or invention',
          'a type of traffic ticket',
          'a dangerous accident',
          'an old, outdated method',
        ],
        correctIndex: 0,
        explanation: 'The passage describes the added warning signal as something new Morgan created, which is what "innovation" means — a new idea or invention.',
      },
      {
        kind: 'main-idea',
        prompt: 'What did Garrett Morgan do in 1916, according to the passage?',
        choices: [
          'He invented the first traffic light in the world',
          'He rescued trapped workers from a flooded, toxic tunnel using his safety hood',
          'He opened a car factory',
          'He was elected mayor of Cleveland',
        ],
        correctIndex: 1,
        explanation: 'The passage says that when the tunnel flooded with toxic gas, "Morgan and his brother put on his safety hoods and went in themselves, rescuing several trapped men."',
      },
      {
        kind: 'inference',
        prompt: "What does the rescue in 1916 suggest about Morgan's safety hood invention?",
        choices: [
          'It was untested and did not work well',
          'It was effective enough to be trusted in a real, dangerous emergency',
          'It was designed only for use in mines',
          'It was never used after that day',
        ],
        correctIndex: 1,
        explanation: 'Morgan trusted his own invention enough to use it in an actual life-or-death rescue, showing it worked well under real pressure.',
      },
    ],
  },
];

export const systemicMoments: SystemicMoment[] = [
  {
    id: 'civil-rights-act-1866',
    title: 'The Veto Override',
    year: '1866',
    setup: `Washington, D.C., April 1866. Eleven months after the war ended, and the country still hasn't decided what freedom actually means. You're a Republican member of the House of Representatives. Weeks ago, Congress passed the Civil Rights Act of 1866 — the first federal law declaring that anyone born in the United States is a citizen, entitled to the same rights as anyone else, regardless of race. President Andrew Johnson vetoed it, calling it federal overreach he says the states should handle on their own. Meanwhile, Southern legislatures have spent the winter passing "Black Codes" — laws that reopened the door to forced labor, banned Black land ownership in whole counties, and let a Black man be arrested for simply being unemployed. Now the House has ten minutes to decide whether to override the President's veto — something no Congress has ever done to a president on a bill this significant. It takes two-thirds, or the bill dies. A colleague leans in: "Where do you stand?"`,
    choices: [
      { id: 'override', label: 'Vote to override — push the Civil Rights Act into law over the veto.' },
      { id: 'sustain', label: 'Vote to sustain the veto — side with Johnson, leave it to the states.' },
      { id: 'abstain', label: 'Abstain — let the rest of the House decide without you.' },
    ],
    realityChoiceId: 'override',
    speculation: {
      sustain:
        "You vote nay. It doesn't matter — the override passes anyway, 122 to 41, with two-thirds to spare. Your name goes into the record on the losing side of one of the most important votes of the era.",
      abstain:
        "You duck the vote. The override passes without you, 122 to 41. History records what happened in that chamber — just not what you would have done in it.",
    },
    matchIntro:
      "That's exactly what happened. The House votes 122 to 41 — enough to clear two-thirds — and the Civil Rights Act of 1866 becomes law over the President's veto, the first time any Congress had done that on a bill this significant.",
    missIntro:
      "The House votes 122 to 41 anyway — enough to clear two-thirds regardless of your vote — and the Civil Rights Act of 1866 becomes law over the President's veto, the first time any Congress had done that on a bill this significant.",
    epilogue:
      "But a law on paper isn't the same as a law enforced. Congress soon worried a future Congress could simply repeal it, so lawmakers wrote its core promise into the Constitution itself as the Fourteenth Amendment. It still wasn't enough. Over the next decade, federal troops enforcing these rights in the South were withdrawn — traded away in an 1877 deal to settle a disputed presidential election. Southern states rewrote their laws to get around the Fourteenth Amendment in every way courts allowed, and by 1896 the Supreme Court itself blessed segregation in Plessy v. Ferguson. The rights this vote protected on paper wouldn't be fully enforced in this country for almost another hundred years.",
    closingLine: 'The vote was right. The story still isn\'t finished — not even now.',
    questions: [
      {
        kind: 'vocab',
        prompt: 'In the story, when the House votes to "override" the President\'s veto, that most nearly means:',
        choices: [
          'Delaying a decision until the next session',
          'Canceling out or overruling someone else\'s decision',
          'Asking a court to review a law',
          'Resigning from your position',
        ],
        correctIndex: 1,
        explanation: 'Overriding the veto means overruling Johnson\'s decision — that\'s exactly what the two-thirds vote did.',
      },
      {
        kind: 'main-idea',
        prompt: "Why did Congress later write the Civil Rights Act's protections into the Fourteenth Amendment instead of leaving them as a regular law?",
        choices: [
          'The Supreme Court ordered them to',
          'A regular law could be undone by a future Congress, but a constitutional amendment is far harder to repeal',
          'President Johnson requested it himself',
          'It was simply faster than passing a new law',
        ],
        correctIndex: 1,
        explanation: 'A plain statute is one Congress away from being undone; writing it into the Constitution protected the Act from a future repeal.',
      },
      {
        kind: 'inference',
        prompt: 'The epilogue ends with troops withdrawn in 1877 and the Supreme Court upholding segregation in Plessy v. Ferguson in 1896. What does that suggest about winning a vote like this one?',
        choices: [
          'Once a law passes, it enforces itself automatically, forever',
          'Passing a law is only the first step — without ongoing enforcement and political will, it can still be undermined',
          'The Civil Rights Act of 1866 was completely forgotten after that year',
          'The Supreme Court has no authority over civil rights laws',
        ],
        correctIndex: 1,
        explanation: "Passing the law was necessary but not sufficient — enforcement turned out to be a separate, ongoing fight that the country lost for decades.",
      },
    ],
  },
];

export const jackieQuest: Quest = {
  id: 'jackie-robinson-quest',
  title: 'Jackie Robinson: Four Lives',
  subject: 'Jackie Robinson',
  chapters: [
    {
      id: 'pepper-street',
      title: 'Pepper Street',
      persona: 'Carl Anderson',
      personaBlurb:
        "You're Carl Anderson, a mechanic who lives near the Robinson family. The neighborhood kids treat your garage as the one place on Pepper Street that'll let them hang around.",
      year: 'Pasadena, California — mid-1930s',
      historicalContext:
        'Pasadena markets itself nationally as a genteel, white resort town — the Rose Bowl, the Tournament of Roses — while restrictive housing covenants and informal rules pen its small Black population into a few blocks, and the public plunge pool is open to Black residents only one day a week.',
      scene:
        "Jackie Robinson, twelve years old, runs with a loose group of neighborhood kids the city calls the \"Pepper Street Gang\" — more bored than criminal, but drifting toward real trouble. Today they turn up at your garage rattled: turned away from the plunge again, on the wrong day, by an attendant who didn't bother explaining why. One of the older boys is already talking about going back tonight to settle it.",
      sceneConfig: {
        sky: ['#4f9be0', '#bfe6ff'],
        ground: '#dab06a',
        groundLine: 0.7,
        accent: { x: 0.82, y: 0.18, r: 0.06, color: '#f7dc6f' },
        weather: 'clouds',
        silhouettes: [
          { x: 0.05, y: 0.55, w: 0.18, h: 0.15, color: '#8a6a45' },
          { x: 0.28, y: 0.5, w: 0.12, h: 0.2, color: '#9c7a52' },
          { x: 0.68, y: 0.45, w: 0.03, h: 0.28, color: '#3a3f8f' },
          { x: 0.75, y: 0.45, w: 0.03, h: 0.28, color: '#3a3f8f' },
          { x: 0.82, y: 0.45, w: 0.03, h: 0.28, color: '#3a3f8f' },
          { x: 0.89, y: 0.45, w: 0.03, h: 0.28, color: '#3a3f8f' },
        ],
      },
      character: 'mechanic',
      characterX: 0.54,
      choices: [
        {
          id: 'confront',
          label: 'Tell them to go back and confront the attendant tonight.',
          isReality: false,
          consequence:
            "You back the older boy's plan. That night, a scuffle at the pool gate ends with two of the boys arrested for trespassing — a record that follows them for years, and does nothing to open the pool.",
        },
        {
          id: 'ignore',
          label: "Tell them to forget it — it's not worth the trouble.",
          isReality: false,
          consequence:
            "You wave it off, and so do they — until the same anger comes out sideways a week later, in a fight two blocks over. Ignoring it didn't make it go away; it just waited for a worse moment.",
        },
        {
          id: 'redirect',
          label: 'Challenge Jackie to a race to the corner and back, right there at the garage.',
          isReality: true,
        },
      ],
      realityText:
        "That's what you really did. You didn't lecture them about the pool — you challenged Jackie to outrun you to the corner and back. He did, easily, and you told him so, straight: that kind of speed was wasted on trouble. It became a habit — you, and later Rev. Karl Downs at the local church, kept finding Jackie games and competitions to channel his energy into instead of letting his group's restlessness curdle into something worse.",
      closingLine: "The record holds — not because you punished him, but because you outran his anger with something better to do.",
      questions: [
        {
          kind: 'vocab',
          prompt: "In the story, to \"channel\" Jackie's energy most nearly means:",
          choices: ['To waste it', 'To direct it toward something specific, like sports', 'To ignore it entirely', 'To punish it'],
          correctIndex: 1,
          explanation: 'Channeling his energy means giving it somewhere useful to go — exactly what the race, and later organized sports, did.',
        },
        {
          kind: 'main-idea',
          prompt: "According to the chapter, why didn't Pasadena's reputation match daily life for the Robinson family?",
          choices: [
            'The city was actually fully integrated',
            'The city marketed itself as an idyllic resort town while enforcing informal segregation, like limiting the public pool to one day a week for Black residents',
            "The Robinsons didn't actually live in Pasadena",
            'There was no pool in Pasadena',
          ],
          correctIndex: 1,
          explanation: "The chapter contrasts Pasadena's genteel public image with the real, informal segregation its Black residents faced.",
        },
        {
          kind: 'inference',
          prompt: "What does Carl Anderson's choice to challenge Jackie to a race, instead of lecturing him, suggest about how he understood young Jackie?",
          choices: [
            "He didn't take Jackie's anger seriously",
            'He recognized Jackie needed a real outlet for his energy, not just a warning',
            'He wanted to prove he was faster than a child',
            "He wasn't interested in Jackie's future",
          ],
          correctIndex: 1,
          explanation: 'Anderson met Jackie\'s restlessness with something to actually do with it, rather than just telling him to stop feeling it.',
        },
      ],
    },
    {
      id: 'fort-hood',
      title: 'The Bus at Camp Hood',
      persona: 'Lieutenant Jackie Robinson',
      personaBlurb: 'You are Second Lieutenant Jackie Robinson, 761st Tank Battalion, Camp Hood, Texas, July 1944.',
      year: 'Camp Hood, Texas — July 1944',
      historicalContext:
        "The U.S. Army is still segregated by law and custom, even as Black soldiers fight and die overseas for a country that treats them as second-class at home. A 1944 War Department order bans segregation on Army post transportation, though many bus drivers ignore it — or don't know about it at all.",
      scene:
        "You board an Army bus on base and sit down next to a friend's wife, roughly in the middle of the bus. The driver glances in his mirror and orders you to move to the back.",
      sceneConfig: {
        sky: ['#e0913f', '#f5dea0'],
        ground: '#b98d4f',
        groundLine: 0.68,
        accent: { x: 0.15, y: 0.2, r: 0.05, color: '#fff3d0' },
        weather: 'clouds',
        silhouettes: [
          { x: 0.1, y: 0.4, w: 0.2, h: 0.1, color: '#4a4a4a' },
          { x: 0.35, y: 0.5, w: 0.15, h: 0.2, color: '#6b5a3a' },
          { x: 0.72, y: 0.5, w: 0.15, h: 0.2, color: '#6b5a3a' },
          { x: 0.92, y: 0.35, w: 0.04, h: 0.35, color: '#3a3a3a' },
        ],
      },
      character: 'soldier',
      characterX: 0.61,
      choices: [
        {
          id: 'comply',
          label: 'Move to the back without a word.',
          isReality: false,
          consequence:
            "You do. It's the easier path in the moment — no confrontation, no report, no risk. But you carry the anger of it, with no telling where it would have come out later instead.",
        },
        {
          id: 'argue-loud',
          label: 'Refuse loudly and argue with the driver in front of everyone.',
          isReality: false,
          consequence:
            "You refuse, but the shouting match draws an MP before you can calmly explain your reasoning. Without a composed account on record, the report paints you as simply combative — a much harder case to defend.",
        },
        {
          id: 'refuse-calm',
          label: 'Refuse calmly, and stay in your seat.',
          isReality: true,
        },
      ],
      realityText:
        "That's exactly what happened. You refused to move — calmly, but without backing down — citing the 1944 order desegregating on-base transportation. Military police were called; you were taken in and later court-martialed on charges including insubordination, which you denied. At trial, your composed, exact testimony carried the case: you were acquitted on every charge.",
      closingLine: 'The record holds — not because it was easy, but because you stayed exactly as calm on trial as you were in that seat.',
      questions: [
        {
          kind: 'vocab',
          prompt: '"Insubordination" most nearly means:',
          choices: ['Refusing to follow orders from someone in authority', 'An award for bravery', 'A type of military vehicle', 'A formal apology'],
          correctIndex: 0,
          explanation: "That's exactly the charge Robinson faced and was acquitted of — refusing an order from a superior.",
        },
        {
          kind: 'main-idea',
          prompt: 'Why was Robinson court-martialed?',
          choices: [
            'For a crime unrelated to the bus incident',
            'For refusing to move to the back of a military bus, on charges including insubordination',
            'For deserting his post',
            'For striking an officer',
          ],
          correctIndex: 1,
          explanation: 'The chapter is built directly around this refusal and the charges that followed it.',
        },
        {
          kind: 'inference',
          prompt: 'What does the outcome of the trial suggest about the importance of how Robinson responded in the moment?',
          choices: [
            'It made no difference — the outcome would have been the same either way',
            'His calm, composed account under real legal pressure was central to the court ruling in his favor',
            'The court was going to acquit him no matter what',
            'Shouting at the driver would have helped his case',
          ],
          correctIndex: 1,
          explanation: 'The text credits his composed testimony, the same quality he showed on the bus, with carrying the case.',
        },
      ],
    },
    {
      id: 'rickey-office',
      title: 'The Office on Montague Street',
      persona: 'Branch Rickey',
      personaBlurb: "You're Branch Rickey, general manager of the Brooklyn Dodgers.",
      year: 'Brooklyn, New York — August 28, 1945',
      historicalContext:
        "Major League Baseball has excluded Black players since the 1880s under an unwritten \"gentleman's agreement.\" You've spent over a year secretly scouting Negro Leagues players, telling reporters you're simply forming a new team as cover for what you're really planning.",
      scene:
        "Jackie Robinson, a shortstop for the Kansas City Monarchs, sits across your desk. You've decided he's the one — disciplined, fast, college-educated, and, crucially, someone you believe can withstand what's coming without fighting back. Now you have to decide how hard to test that, right here in the room, before you offer him anything.",
      sceneConfig: {
        sky: ['#242863', '#7a5fc4'],
        ground: '#1a1206',
        groundLine: 0.72,
        accent: { x: 0.5, y: 0.15, r: 0.04, color: '#f0ecd6' },
        twinkles: [
          { x: 0.1, y: 0.08, r: 0.004, color: '#ffffff', phase: 0.2 },
          { x: 0.3, y: 0.12, r: 0.004, color: '#ffffff', phase: 1.4 },
          { x: 0.7, y: 0.06, r: 0.004, color: '#ffffff', phase: 2.6 },
          { x: 0.9, y: 0.14, r: 0.004, color: '#ffffff', phase: 0.8 },
          { x: 0.45, y: 0.05, r: 0.004, color: '#ffffff', phase: 3.5 },
          { x: 0.24, y: 0.25, r: 0.006, color: '#f2d879', phase: 1.0 },
          { x: 0.63, y: 0.3, r: 0.006, color: '#f2d879', phase: 2.2 },
        ],
        silhouettes: [
          { x: 0.02, y: 0.25, w: 0.14, h: 0.5, color: '#14172e' },
          { x: 0.2, y: 0.15, w: 0.12, h: 0.6, color: '#1c2040' },
          { x: 0.36, y: 0.35, w: 0.1, h: 0.4, color: '#14172e' },
          { x: 0.6, y: 0.2, w: 0.13, h: 0.55, color: '#1c2040' },
          { x: 0.78, y: 0.3, w: 0.1, h: 0.45, color: '#14172e' },
        ],
      },
      character: 'suit',
      characterX: 0.52,
      choices: [
        {
          id: 'offer-plain',
          label: 'Simply offer him the contract and hope for the best.',
          isReality: false,
          consequence:
            "You sign him without ever testing his temperament. It's a gamble — without knowing for certain he can hold his composure under the abuse to come, you send him into the league blind, with no shared understanding of what he's agreed to endure.",
        },
        {
          id: 'discourage',
          label: "Warn him off — tell him it's too dangerous and not worth the risk.",
          isReality: false,
          consequence:
            "You talk him out of it. Baseball's color line holds for a while longer, waiting for another team, another executive, another player willing to take the same risk, someday.",
        },
        {
          id: 'provoke',
          label: "Act out the exact abuse he'll face — a hostile clerk, an opposing player, a screaming fan — and watch how he responds.",
          isReality: true,
        },
      ],
      realityText:
        "That's exactly what you did. In that meeting, you played the part of a racist hotel clerk, an opposing player, a screaming fan — pushing Robinson as hard in that room as the world would push him on the field. When he finally asked if you wanted a player \"afraid to fight back,\" you told him the truth: you wanted a player with guts enough not to. He agreed. On April 15, 1947, he started at first base for the Brooklyn Dodgers — the first Black player in the modern major leagues.",
      closingLine: 'The record holds — because you needed to know, before either of you risked everything, that he actually could.',
      questions: [
        {
          kind: 'vocab',
          prompt: 'To "provoke" someone most nearly means:',
          choices: ['To calm them down', 'To deliberately trigger a reaction from them', 'To pay them a compliment', 'To ignore them completely'],
          correctIndex: 1,
          explanation: "That's exactly what Rickey did — deliberately acting out abuse to see how Robinson would react.",
        },
        {
          kind: 'main-idea',
          prompt: 'Why did Rickey act out abusive scenarios in front of Robinson before offering him a contract?',
          choices: [
            'He enjoyed being cruel',
            'He needed to know Robinson could withstand real abuse without retaliating, since retaliating would end the whole plan',
            'It was a standard tryout for every player',
            "He was testing Robinson's batting swing",
          ],
          correctIndex: 1,
          explanation: "The chapter frames this as a deliberate test of temperament, not cruelty for its own sake.",
        },
        {
          kind: 'inference',
          prompt: "What does Robinson's agreement in that meeting suggest about the deal he made with Rickey?",
          choices: [
            'He had no real choice in the matter',
            'He knowingly accepted a specific, difficult personal sacrifice in exchange for the chance to break the color line',
            "He didn't understand what he was agreeing to",
            'Rickey forced him against his will',
          ],
          correctIndex: 1,
          explanation: 'Robinson understood exactly what he was signing up for — the chapter shows him asking Rickey directly what kind of player he wanted.',
        },
      ],
    },
    {
      id: 'standing-beside-him',
      title: 'Standing Beside Him',
      persona: 'Pee Wee Reese',
      personaBlurb: "You're Pee Wee Reese, the Dodgers' shortstop and team captain.",
      year: 'A road game, 1947',
      historicalContext:
        "Robinson's rookie season draws relentless hostility — hate mail, opposing bench jockeying, and open threats in some cities. Several of Robinson's own teammates had circulated a petition refusing to play alongside him before the team's manager shut it down.",
      scene:
        "During a road game, fans and opposing players are shouting at Robinson from the stands and the dugout alike. You're the team's captain, a well-liked, Kentucky-born infielder, standing near him on the field.",
      sceneConfig: {
        sky: ['#3a85d9', '#a8dfff'],
        ground: '#33c17a',
        groundLine: 0.62,
        accent: { x: 0.85, y: 0.15, r: 0.06, color: '#fff3d0' },
        weather: 'clouds',
        silhouettes: [
          { x: 0, y: 0.35, w: 1, h: 0.16, color: '#8a8f9a' },
          { x: 0, y: 0.36, w: 1, h: 0.02, color: '#5b6070' },
          { x: 0.45, y: 0.66, w: 0.1, h: 0.08, color: '#c9a86b' },
        ],
      },
      character: 'ballplayer',
      characterX: 0.25,
      choices: [
        {
          id: 'ignore-focus',
          label: "Stay focused on the game and ignore it — let your play speak for itself.",
          isReality: false,
          consequence:
            "You keep your head down and play your position. It's not unkind, exactly, but it does nothing to answer the moment — and the crowd, sensing no pushback at all, only gets louder.",
        },
        {
          id: 'confront-crowd',
          label: 'Shout back at the crowd yourself.',
          isReality: false,
          consequence:
            'You turn and yell back. It feels satisfying for a second, but it escalates into a shouting match between the stands and the field, without changing how Robinson is treated once the noise dies down.',
        },
        {
          id: 'stand-beside',
          label: 'Walk over and stand beside him, arm on his shoulder, in full view of the crowd.',
          isReality: true,
        },
      ],
      realityText:
        "That's exactly what you did. In front of a hostile crowd, you walked over to Robinson at his position and put your arm around him — a simple, public gesture from a popular white teammate that needed no words. It didn't end the abuse Robinson faced that season, but it told both benches, and the stands, exactly where the team's captain stood.",
      closingLine: 'The record holds — because sometimes standing next to someone, in plain sight, says everything that needs saying.',
      questions: [
        {
          kind: 'vocab',
          prompt: '"Hostile" most nearly means:',
          choices: ['Friendly and welcoming', 'Unfriendly or aggressively opposed', 'Quiet and indifferent', 'Confused'],
          correctIndex: 1,
          explanation: 'The hostile crowd is the one shouting and threatening — the opposite of welcoming.',
        },
        {
          kind: 'main-idea',
          prompt: 'What did Pee Wee Reese actually do in this moment?',
          choices: [
            "He argued with the crowd on Robinson's behalf",
            'He publicly stood beside Robinson with a hand on his shoulder, in front of a hostile crowd',
            'He asked to be traded to a different team',
            'He refused to play that day',
          ],
          correctIndex: 1,
          explanation: 'The chapter is built around this specific, real, public gesture.',
        },
        {
          kind: 'inference',
          prompt: "What does the chapter suggest about why Reese's gesture mattered, even though it didn't stop the abuse?",
          choices: [
            'It was meaningless since the hostility continued',
            'A public, visible show of solidarity from a respected teammate carried its own impact, separate from whether it silenced the crowd',
            'It only mattered to Reese himself',
            'It made the crowd immediately stop and apologize',
          ],
          correctIndex: 1,
          explanation: "The chapter is careful to say it didn't end the abuse, while still treating the gesture as meaningful in its own right.",
        },
      ],
    },
  ],
};
