import type { Passage } from './types';

export const passages: Passage[] = [
  {
    id: 'harriet-tubman',
    name: 'Harriet Tubman',
    years: 'c. 1822–1913',
    text: `Harriet Tubman was born into slavery in Maryland around 1822. In 1849, she escaped to freedom in the North. She could have stayed safe, but instead she went back again and again. Using a secret network called the Underground Railroad, Tubman guided about seventy enslaved people to freedom over thirteen dangerous trips. She traveled at night, avoided slave catchers, and never lost a single passenger. Her friends called her "Moses" because she led her people, like the Bible's Moses, out of bondage. During the Civil War, Tubman also served the Union Army as a scout and spy. Her <vocab>relentless</vocab> courage never faded, even when a bounty was placed on her head.`,
    vocabWord: 'relentless',
    vocabDefinition: 'not stopping or giving up, even when things are difficult',
    funFact: 'Tubman never lost a single passenger on any of her thirteen trips.',
    questions: [
      {
        kind: 'vocab',
        prompt: 'In the passage, the word "relentless" most nearly means:',
        choices: [
          'careless and confused',
          'not stopping or giving up',
          'quiet and shy',
          'brief and sudden',
        ],
        correctIndex: 1,
        explanation: 'Relentless describes courage that never faded, even with a bounty on her head — meaning it never stopped or wavered.',
      },
      {
        kind: 'main-idea',
        prompt: 'What was the Underground Railroad, as described in the passage?',
        choices: [
          'An actual railroad with trains',
          'A secret network that helped enslaved people escape',
          'A group of Union Army spies',
          'A law that ended slavery',
        ],
        correctIndex: 1,
        explanation: 'The passage says Tubman used "a secret network called the Underground Railroad" to guide people to freedom.',
      },
      {
        kind: 'inference',
        prompt: "Based on the passage, why did people call Harriet Tubman 'Moses'?",
        choices: [
          'Because that was her real name',
          'Because she wrote a famous book',
          "Because, like the Bible's Moses, she led her people out of bondage",
          'Because she was born in Egypt',
        ],
        correctIndex: 2,
        explanation: 'The passage directly compares her to Moses because she led her people out of slavery, just as Moses led his people out of bondage.',
      },
    ],
  },
  {
    id: 'frederick-douglass',
    name: 'Frederick Douglass',
    years: '1818–1895',
    text: `Frederick Douglass was born enslaved in Maryland in 1818. Enslaved people were forbidden from learning to read, but Douglass secretly taught himself letters with the help of children in his neighborhood. Reading opened his mind to the idea that slavery was wrong and could be fought. In 1838, he escaped to New York and became a powerful <vocab>abolitionist</vocab>, traveling from town to town to convince Americans that slavery must end. Douglass gave fiery speeches, wrote a bestselling autobiography, and published his own newspaper, The North Star, to spread his message further. During the Civil War, he pushed President Lincoln to let Black soldiers fight for the Union. Douglass believed that words and ideas were as powerful as any weapon.`,
    vocabWord: 'abolitionist',
    vocabDefinition: 'a person who worked to end slavery',
    funFact: 'Douglass taught himself to read and write in secret, since it was illegal to teach enslaved people.',
    questions: [
      {
        kind: 'vocab',
        prompt: 'As used in the passage, "abolitionist" most nearly means:',
        choices: [
          'a person who worked to end slavery',
          'a newspaper editor',
          'a soldier in the Union Army',
          'a teacher of young children',
        ],
        correctIndex: 0,
        explanation: 'The passage shows Douglass traveling to "convince Americans that slavery must end" — that work is what makes someone an abolitionist.',
      },
      {
        kind: 'main-idea',
        prompt: 'How did Douglass spread his message, according to the passage?',
        choices: [
          'Only through private conversations',
          'By giving speeches, writing an autobiography, and publishing a newspaper',
          'By running for political office',
          'By working directly for the government',
        ],
        correctIndex: 1,
        explanation: 'The passage lists speeches, a bestselling autobiography, and his newspaper The North Star as ways he spread his message.',
      },
      {
        kind: 'inference',
        prompt: 'What does the passage suggest about the importance of reading in Douglass\'s life?',
        choices: [
          'Reading had little effect on his beliefs',
          'Reading was only useful for entertainment',
          'Learning to read helped him realize slavery was wrong and gave him the tools to fight it',
          'He never learned to read fluently',
        ],
        correctIndex: 2,
        explanation: 'The passage says reading "opened his mind" to slavery being wrong, and his skill with words later became his main tool as an activist.',
      },
    ],
  },
  {
    id: 'rosa-parks',
    name: 'Rosa Parks',
    years: '1913–2005',
    text: `On December 1, 1955, Rosa Parks boarded a bus in Montgomery, Alabama, after a long day of work. When the driver ordered her to give up her seat to a white passenger, she quietly refused. Parks was arrested, but her small act of defiance sparked a huge response. Black leaders in Montgomery organized a <vocab>boycott</vocab> of the city buses, urging riders to walk, carpool, or find any other way to get around instead of riding. For 381 days, thousands of people kept up the boycott, even in bad weather. The bus company lost so much money that the city was finally forced to end segregated seating. Parks had been a civil rights activist for years before that day, but her calm courage on the bus made her a symbol for the whole movement.`,
    vocabWord: 'boycott',
    vocabDefinition: 'an organized refusal to buy from or use something, done to force a change',
    funFact: 'The Montgomery Bus Boycott lasted 381 days before the city ended segregated seating.',
    questions: [
      {
        kind: 'vocab',
        prompt: 'As used in the passage, the word "boycott" most nearly means:',
        choices: [
          'a type of bus route',
          'an organized refusal to use something as a protest',
          'a legal punishment for breaking a law',
          'a celebration held after a victory',
        ],
        correctIndex: 1,
        explanation: 'The passage explains that leaders organized a boycott by urging riders to avoid the buses altogether — an organized refusal used to pressure the company.',
      },
      {
        kind: 'main-idea',
        prompt: 'Why did the bus company eventually end segregated seating?',
        choices: [
          'A new law was passed overnight',
          'Rosa Parks sued the company in court',
          'It lost so much money during the 381-day boycott',
          'The bus drivers went on strike',
        ],
        correctIndex: 2,
        explanation: 'The passage says the boycott lasted 381 days and the bus company "lost so much money" that the city was forced to act.',
      },
      {
        kind: 'inference',
        prompt: "What does the passage suggest about Rosa Parks's role in the civil rights movement?",
        choices: [
          'She acted alone and had no connection to any larger movement',
          'She had no interest in civil rights before 1955',
          'She was already an activist, and her arrest became a spark that ignited a much larger protest',
          'She was a bus driver herself',
        ],
        correctIndex: 2,
        explanation: 'The passage notes Parks "had been a civil rights activist for years before that day," and her arrest "sparked" the larger boycott.',
      },
    ],
  },
  {
    id: 'martin-luther-king-jr',
    name: 'Martin Luther King Jr.',
    years: '1929–1968',
    text: `Martin Luther King Jr. was a Baptist minister who became the most famous leader of the American civil rights movement. King believed that protests should always be <vocab>nonviolent</vocab>, even when protesters were met with violence themselves. He organized marches, boycotts, and sit-ins across the South, and he was arrested many times for his activism. In August 1963, King stood before a quarter of a million people in Washington, D.C., and delivered his famous "I Have a Dream" speech, calling for an end to racism and inequality. In 1964, he became the youngest person at the time to win the Nobel Peace Prize. King was assassinated in 1968, but the laws his movement helped pass, like the Civil Rights Act, changed the country forever.`,
    vocabWord: 'nonviolent',
    vocabDefinition: 'not using physical force or violence',
    funFact: 'In 1964, King became the youngest person up to that time to win the Nobel Peace Prize.',
    questions: [
      {
        kind: 'vocab',
        prompt: 'In the passage, the word "nonviolent" most nearly means:',
        choices: [
          'secret and hidden',
          'not using physical force',
          'extremely loud',
          'planned far in advance',
        ],
        correctIndex: 1,
        explanation: 'The passage contrasts nonviolent protest with the violence protesters faced, showing that nonviolent means not using physical force.',
      },
      {
        kind: 'main-idea',
        prompt: 'What happened in August 1963, according to the passage?',
        choices: [
          'King won the Nobel Peace Prize',
          'King was arrested for the first time',
          'King delivered his "I Have a Dream" speech to a quarter of a million people',
          'The Civil Rights Act was signed into law',
        ],
        correctIndex: 2,
        explanation: 'The passage states that "In August 1963, King stood before a quarter of a million people... and delivered his famous \'I Have a Dream\' speech."',
      },
      {
        kind: 'inference',
        prompt: "Based on the passage, why was King's commitment to nonviolence especially difficult?",
        choices: [
          'Because no one supported his cause',
          'Because he faced violence in return but still refused to use it himself',
          'Because nonviolent protests were against the law',
          'Because he preferred to protest alone',
        ],
        correctIndex: 1,
        explanation: 'The passage says protests stayed nonviolent "even when protesters were met with violence themselves," showing King held to his principle despite being attacked.',
      },
    ],
  },
  {
    id: 'bessie-coleman',
    name: 'Bessie Coleman',
    years: '1892–1926',
    text: `Bessie Coleman grew up picking cotton in Texas, but she dreamed of flying. In the early 1900s, American flight schools refused to train her because she was Black and a woman. Determined, Coleman learned French and traveled to France, where she earned her pilot's license in 1921 — the first African American and the first Native American woman ever to do so. Back in the United States, no one would hire her to fly for an airline, so she became a <vocab>barnstorming</vocab> pilot, thrilling crowds at air shows with daring loops, dives, and figure eights. She also refused to perform anywhere that separated Black and white spectators. Coleman died in a flying accident in 1926, but she had already inspired a generation of Black aviators.`,
    vocabWord: 'barnstorming',
    vocabDefinition: 'performing daring, showy flying stunts to entertain a crowd',
    funFact: 'Coleman had to travel all the way to France to find a flight school that would train her.',
    questions: [
      {
        kind: 'vocab',
        prompt: 'As used in the passage, "barnstorming" most nearly means:',
        choices: [
          'farming in the countryside',
          'performing daring flying stunts for crowds',
          'teaching new pilots to fly',
          'repairing broken airplanes',
        ],
        correctIndex: 1,
        explanation: 'The passage describes Coleman "thrilling crowds at air shows with daring loops, dives, and figure eights," which is what a barnstorming pilot does.',
      },
      {
        kind: 'main-idea',
        prompt: 'Why did Bessie Coleman travel to France?',
        choices: [
          'To visit family',
          'Because American flight schools refused to train her',
          'To compete in an international air race',
          'To study cotton farming methods',
        ],
        correctIndex: 1,
        explanation: 'The passage says American flight schools refused to train her because of her race and gender, so she went to France instead.',
      },
      {
        kind: 'inference',
        prompt: "What does Coleman's refusal to perform at segregated air shows suggest about her?",
        choices: [
          'She only cared about her own fame',
          'She avoided controversy whenever possible',
          'She used her position to stand up against unfair treatment of Black spectators',
          'She was afraid of large crowds',
        ],
        correctIndex: 2,
        explanation: 'By refusing to perform where audiences were segregated, Coleman used her influence to push back against unequal treatment, not just to entertain.',
      },
    ],
  },
  {
    id: 'katherine-johnson',
    name: 'Katherine Johnson',
    years: '1918–2020',
    text: `Katherine Johnson loved numbers from the time she was a child, and she graduated from college at just eighteen years old. She went to work for NASA as a mathematician, at a time when Black women were placed in a separate office called the "West Computing" group. Johnson calculated the flight path, or <vocab>trajectory</vocab>, for America's first crewed spaceflight in 1961. Her work was so trusted that before his historic orbit around Earth, astronaut John Glenn asked engineers to have Johnson personally check the numbers produced by NASA's new electronic computers by hand. If her numbers matched the computer's, he said, he would trust the flight. They matched. Johnson's calculations later helped guide the Apollo 11 mission to the moon.`,
    vocabWord: 'trajectory',
    vocabDefinition: 'the curved path that an object follows as it moves through space',
    funFact: "John Glenn wouldn't fly until Katherine Johnson personally checked the computer's math.",
    questions: [
      {
        kind: 'vocab',
        prompt: 'In the passage, "trajectory" most nearly means:',
        choices: [
          'the fuel used by a rocket',
          'the path an object follows as it moves',
          'the weight of a spacecraft',
          'a type of mathematical equation',
        ],
        correctIndex: 1,
        explanation: 'The passage explains that trajectory refers to the flight path Johnson calculated for the spacecraft.',
      },
      {
        kind: 'main-idea',
        prompt: "Why did John Glenn want Katherine Johnson to check the computer's numbers by hand?",
        choices: [
          'The computer was broken',
          "He trusted her calculations and wanted to confirm the computer's results matched hers",
          'NASA did not own enough computers',
          'Johnson had invented the computer',
        ],
        correctIndex: 1,
        explanation: "The passage says Glenn wanted Johnson to check the numbers because he trusted her math, and he would only fly if her numbers matched the computer's.",
      },
      {
        kind: 'inference',
        prompt: "What does the passage suggest about the value of Katherine Johnson's work at NASA?",
        choices: [
          "It was considered unimportant compared to the engineers' work",
          "It was so trusted that a famous astronaut's safety depended on her checking it",
          'It was only used for minor calculations',
          'It was replaced entirely once computers were invented',
        ],
        correctIndex: 1,
        explanation: "Glenn trusted Johnson's calculations enough to base his willingness to fly on whether they matched the computer, showing how vital her work was.",
      },
    ],
  },
  {
    id: 'jackie-robinson',
    name: 'Jackie Robinson',
    years: '1919–1972',
    text: `In 1947, Jackie Robinson stepped onto the field as a Brooklyn Dodger and broke Major League Baseball's color line, becoming the first Black player in the modern era. Team executive Branch Rickey had warned Robinson that he would face terrible abuse — insults, threats, and even opposing players trying to injure him — and asked him to respond without fighting back. Robinson agreed, showing incredible <vocab>restraint</vocab> as fans and opponents hurled racist insults at him game after game. He let his performance on the field speak instead, winning Rookie of the Year in 1947 and the National League MVP award in 1949. Robinson's success proved that Black athletes belonged in the major leagues and opened the door for the integration of professional sports.`,
    vocabWord: 'restraint',
    vocabDefinition: 'the ability to control your feelings or actions, especially when provoked',
    funFact: 'Robinson won Rookie of the Year in 1947 and league MVP just two seasons later, in 1949.',
    questions: [
      {
        kind: 'vocab',
        prompt: 'As used in the passage, "restraint" most nearly means:',
        choices: [
          'controlling your feelings or actions instead of reacting',
          'a special piece of baseball equipment',
          "a rule written into baseball's official handbook",
          'a type of injury',
        ],
        correctIndex: 0,
        explanation: 'The passage shows Robinson responding to abuse "without fighting back," which is what restraint means — controlling your reaction instead of lashing out.',
      },
      {
        kind: 'main-idea',
        prompt: 'What did Branch Rickey ask Jackie Robinson to do?',
        choices: [
          'Quit baseball after one season',
          'Face abuse without fighting back',
          'Train other Black players',
          'Move to a different team',
        ],
        correctIndex: 1,
        explanation: 'The passage states Rickey "asked him to respond without fighting back" despite the abuse Robinson would face.',
      },
      {
        kind: 'inference',
        prompt: "Based on the passage, why was Robinson's approach effective in changing baseball?",
        choices: [
          'He avoided all attention from fans and media',
          'He let his skill on the field prove Black players belonged, rather than reacting to insults',
          'He refused to play until conditions improved',
          'He convinced Rickey to ban all opposing teams',
        ],
        correctIndex: 1,
        explanation: 'The passage says Robinson "let his performance on the field speak," and his success "proved that Black athletes belonged," showing that his skill, not conflict, changed minds.',
      },
    ],
  },
  {
    id: 'madam-cj-walker',
    name: 'Madam C.J. Walker',
    years: '1867–1919',
    text: `Sarah Breedlove was born in 1867 to formerly enslaved parents in Louisiana. After struggling with her own hair loss, she developed a line of hair care products made especially for Black women, and rebranded herself as Madam C.J. Walker. Rather than just selling her products in stores, Walker built a <vocab>self-made</vocab> business empire by training thousands of Black women as sales agents who sold door to door and earned real income of their own. By the early 1900s, Walker had become one of the first American women, of any race, to become a millionaire. She spent much of her fortune funding scholarships, orphanages, and civil rights organizations, believing that Black economic success was tied to Black freedom.`,
    vocabWord: 'self-made',
    vocabDefinition: 'having become successful through your own hard work rather than inherited wealth',
    funFact: 'Walker trained thousands of Black women as sales agents, giving them their own source of income.',
    questions: [
      {
        kind: 'vocab',
        prompt: 'In the passage, "self-made" most nearly means:',
        choices: [
          'inheriting money from a wealthy family',
          'becoming successful through your own hard work',
          "working for someone else's company",
          'borrowing money to start a business',
        ],
        correctIndex: 1,
        explanation: "The passage describes Walker building her fortune herself, from a personal struggle to a business empire, which is what \"self-made\" describes.",
      },
      {
        kind: 'main-idea',
        prompt: "How did Madam C.J. Walker build her business, according to the passage?",
        choices: [
          'By opening a single store in Louisiana',
          'By training thousands of women as sales agents who sold door to door',
          'By inheriting a hair care company',
          'By working exclusively with department stores',
        ],
        correctIndex: 1,
        explanation: 'The passage says Walker "built a self-made business empire by training thousands of Black women as sales agents."',
      },
      {
        kind: 'inference',
        prompt: "What can you infer about Walker's beliefs from how she used her fortune?",
        choices: [
          'She believed money should only benefit her own family',
          "She believed economic success for Black Americans was connected to their freedom and opportunity",
          'She had no interest in civil rights',
          'She wanted to keep her wealth a secret',
        ],
        correctIndex: 1,
        explanation: 'The passage says she funded scholarships, orphanages, and civil rights groups because she believed "Black economic success was tied to Black freedom."',
      },
    ],
  },
  {
    id: 'shirley-chisholm',
    name: 'Shirley Chisholm',
    years: '1924–2005',
    text: `In 1968, Shirley Chisholm became the first Black woman elected to the United States Congress, representing part of New York. She was known for being outspoken and independent, refusing to simply go along with what powerful party leaders wanted. Her campaign slogan, "unbought and <vocab>unbossed</vocab>," captured her promise that no one — not wealthy donors, not political parties — would control her votes. In 1972, Chisholm made history again by running for President of the United States, becoming the first Black candidate to seek a major party's nomination. She did not win, but her campaign opened doors for the many women and people of color who ran for president after her.`,
    vocabWord: 'unbossed',
    vocabDefinition: 'not controlled or told what to do by anyone',
    funFact: "Chisholm's 1972 presidential run made her the first Black candidate to seek a major party's nomination.",
    questions: [
      {
        kind: 'vocab',
        prompt: 'As used in the passage, "unbossed" most nearly means:',
        choices: [
          'unemployed',
          'not controlled or told what to do by anyone',
          'extremely wealthy',
          'newly elected',
        ],
        correctIndex: 1,
        explanation: 'The passage explains her slogan meant that "no one... would control her votes," which is what "unbossed" describes.',
      },
      {
        kind: 'main-idea',
        prompt: 'What did Shirley Chisholm accomplish in 1972?',
        choices: [
          'She was elected President of the United States',
          "She became the first Black candidate to seek a major party's presidential nomination",
          'She retired from Congress',
          'She wrote a bestselling book',
        ],
        correctIndex: 1,
        explanation: 'The passage says that in 1972 she became "the first Black candidate to seek a major party\'s nomination."',
      },
      {
        kind: 'inference',
        prompt: "What does the passage suggest about the impact of Chisholm's 1972 campaign?",
        choices: [
          'It had no lasting effect on politics',
          'It discouraged other candidates from running',
          'It helped open the door for future women and candidates of color to run for president',
          'It ended her political career immediately',
        ],
        correctIndex: 2,
        explanation: 'The passage states her campaign "opened doors for the many women and people of color who ran for president after her."',
      },
    ],
  },
  {
    id: 'garrett-morgan',
    name: 'Garrett Morgan',
    years: '1877–1963',
    text: `Garrett Morgan was a Black inventor and businessman in Cleveland, Ohio, in the early 1900s. Worried about the number of accidents at busy intersections, Morgan patented an early version of the traffic signal that included a warning position between "stop" and "go," an <vocab>innovation</vocab> that gave drivers time to slow down safely. Morgan also invented a safety hood, an early type of gas mask, designed to help people breathe in smoky or toxic air. In 1916, when a tunnel under Lake Erie flooded with toxic gas and trapped a crew of workers, Morgan and his brother put on his safety hoods and went in themselves, rescuing several trapped men. Many of Morgan's inventions later became standard safety equipment used around the world.`,
    vocabWord: 'innovation',
    vocabDefinition: 'a new idea, method, or invention',
    funFact: 'Morgan used his own gas mask invention to rescue trapped workers from a flooded tunnel in 1916.',
    questions: [
      {
        kind: 'vocab',
        prompt: 'In the passage, "innovation" most nearly means:',
        choices: [
          'a new idea or invention',
          'a type of traffic ticket',
          'a dangerous accident',
          'an old, outdated method',
        ],
        correctIndex: 0,
        explanation: 'The passage describes the added warning signal as something new Morgan created, which is what "innovation" means — a new idea or invention.',
      },
      {
        kind: 'main-idea',
        prompt: 'What did Garrett Morgan do in 1916, according to the passage?',
        choices: [
          'He invented the first traffic light in the world',
          'He rescued trapped workers from a flooded, toxic tunnel using his safety hood',
          'He opened a car factory',
          'He was elected mayor of Cleveland',
        ],
        correctIndex: 1,
        explanation: 'The passage says that when the tunnel flooded with toxic gas, "Morgan and his brother put on his safety hoods and went in themselves, rescuing several trapped men."',
      },
      {
        kind: 'inference',
        prompt: "What does the rescue in 1916 suggest about Morgan's safety hood invention?",
        choices: [
          'It was untested and did not work well',
          'It was effective enough to be trusted in a real, dangerous emergency',
          'It was designed only for use in mines',
          'It was never used after that day',
        ],
        correctIndex: 1,
        explanation: 'Morgan trusted his own invention enough to use it in an actual life-or-death rescue, showing it worked well under real pressure.',
      },
    ],
  },
];
